  server:
    port: 8021
  spring:
#项目名
    application:
      name: rabbitmq-provider
#配置rabbitmq服务器
  rabbitmq:
    host: localhost
    port: 5672
    username: root
    password: root
#虚拟host 可以不设置，使用server默认host
  virtual-host: JCcccHost